# ============================================================================
.helpers/image-structure-test/setup:
  before_script:
    - |
      # --- helpers/image-structure-test/setup -------------------------------
      JOB_SOCKET_PATH=/var/tmp/${CI_JOB_ID}.sock
      export DOCKER_HOST=unix://${JOB_SOCKET_PATH}
      podman system service --time=300 ${DOCKER_HOST} &
      PODMAN_SERVICE_PID=$!


# ============================================================================
.helpers/image-structure-test/teardown:
  before_script:
    - |
      # --- helpers/image-structure-test/teardown ----------------------------
      kill -9 ${PODMAN_SERVICE_PID}
