# ============================================================================
include:
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/cicd-tools/all@release/0.2
  - local: helpers/image-build.gitlab-ci.yml
  - local: helpers/image-registry.gitlab-ci.yml
  - local: helpers/image-structure-test.gitlab-ci.yml


# ============================================================================
.image-base:
  image: $CI_REGISTRY/kerrys-learning-lab/devsecops/cicd-catalog/image:release-0.2
  variables:
    IMAGE_NAME: ''
    IMAGE_TARGET: ''
    IMAGE_INTERIM_TAG: build.${CI_PIPELINE_IID}
    VERY_VERBOSE: "false"
  before_script:
    - !reference [.helpers/registry/login-ci-registry,    before_script]
    - !reference [.helpers/registry/login-base-registry,  before_script]
    - |
      # --- image base (before) ----------------------------------------------

      # ----------------------------------------------------------------------
      # Image identity:
      IMAGE_URI=${CI_REGISTRY_IMAGE}

      if [[ -z "${IMAGE_NAME}" && -n "${IMAGE_TARGET}" ]]; then
        IMAGE_NAME=${IMAGE_TARGET}
      fi

      if [[ -n "${IMAGE_NAME}" ]]; then
        IMAGE_URI+=/${IMAGE_NAME}
      else
        IMAGE_NAME=$(basename ${IMAGE_URI})
      fi


# ============================================================================
.image-build:
  stage: build
  extends: .image-base
  interruptible: true
  variables:
    IMAGE_CONTEXT: .
    IMAGE_DOCKERFILE: Dockerfile
    IMAGE_IGNOREFILE: .dockerignore
    IMAGE_BUILD_CACHE_MODE: default
    IMAGE_BUILD_PUSH_INTERIM: true
    IMAGE_BUILD_PRINT_CLI_TABLE: true
  before_script:
    - !reference [.image-base,                      before_script]
    - !reference [.helpers/image-build/labels,      before_script]
    - !reference [.helpers/image-build/build-args,  before_script]
    - !reference [.helpers/image-build/secrets,     before_script]
    - |
      # --- image build (before) ---------------------------------------------
      PODMAN_BUILD_CLI_ARGS+=(--tag ${IMAGE_URI}:${IMAGE_INTERIM_TAG})


      # ----------------------------------------------------------------------
      # Dockerfile:
      IMAGE_DOCKERFILE=${IMAGE_DOCKERFILE:-Dockerfile}
      if [[ -f ${IMAGE_CONTEXT}/${IMAGE_DOCKERFILE} ]]; then
        IMAGE_DOCKERFILE=${IMAGE_CONTEXT}/${IMAGE_DOCKERFILE}
      fi
      PODMAN_BUILD_CLI_ARGS+=(--file ${IMAGE_DOCKERFILE})


      # ----------------------------------------------------------------------
      # Ignorefile:
      if [[ -f ${IMAGE_CONTEXT}/${IMAGE_IGNOREFILE} ]]; then
        IMAGE_IGNOREFILE=${IMAGE_CONTEXT}/${IMAGE_IGNOREFILE}
      fi
      if [[ -f ${IMAGE_IGNOREFILE} ]]; then
        PODMAN_BUILD_CLI_ARGS+=(--ignorefile ${IMAGE_IGNOREFILE})
      fi


      # ----------------------------------------------------------------------
      # Custom build target, if applicable:
      if [[ -n "${IMAGE_TARGET}" ]]; then
        PODMAN_BUILD_CLI_ARGS+=(--target ${IMAGE_TARGET})
      fi


      # ----------------------------------------------------------------------
      # Cache, if applicable:
      PODMAN_BUILD_CLI_ARGS+=(--layers)
      if [[ ${IMAGE_BUILD_CACHE_MODE} =~ ^(default|from|force)$ ]]; then
        PODMAN_BUILD_CLI_ARGS+=(--cache-from=${IMAGE_URI})
      fi
      if [[ ${IMAGE_BUILD_CACHE_MODE} == force ||
            (${IMAGE_BUILD_CACHE_MODE} =~ ^(default|to)$  &&  ${CI_COMMIT_REF_PROTECTED} == true) ]]; then
        PODMAN_BUILD_CLI_ARGS+=(--cache-to=${IMAGE_URI})
      fi

      # ----------------------------------------------------------------------
      # Labels, build-args, and secrets (calculated above):
      for label in "${IMAGE_LABELS[@]}"; do
        PODMAN_BUILD_CLI_ARGS+=(--label "${label}")
      done

      for arg in "${IMAGE_BUILD_ARGS[@]}"; do
        PODMAN_BUILD_CLI_ARGS+=(--build-arg "${arg}")
      done

      for secret in "${IMAGE_SECRETS[@]}"; do
        PODMAN_BUILD_CLI_ARGS+=(--secret "${secret}")
      done


      # ----------------------------------------------------------------------
      # Context (must be the last argument, it's positional)
      PODMAN_BUILD_CLI_ARGS+=(${IMAGE_CONTEXT})

    - !reference [.helpers/image-build/calculate-job-settings,  before_script]
    - !reference [default,                                      before_script]
  script:
    - |
      # --- image build ------------------------------------------------------
      echo "🛠️ Building ${IMAGE_URI}:${IMAGE_INTERIM_TAG}"

      podman image build "${PODMAN_BUILD_CLI_ARGS[@]}"

      if [[ ${IMAGE_BUILD_PUSH_INTERIM} == true ]]; then
        podman image push --quiet ${IMAGE_URI}:${IMAGE_INTERIM_TAG}
      fi


# ============================================================================
# Unit tests this image
.image-unit-test:
  extends: .image-build
  stage: test
  variables:
    IMAGE_TARGET: unittest
    IMAGE_BUILD_PUSH_INTERIM: false
    IMAGE_BUILD_CACHE_MODE: none
    CONTAINER_RESULTS_PATH: /var/tmp/test-results.xml # Location *within the
                                                      # container* where xunit
                                                      # report will be written
  before_script:
    - !reference [.image-build,       before_script]
    - !reference [.image-build,       script]
    - |
      # --- image unit-test (before) -----------------------------------------
      mkdir -p ${JOB_ARTIFACTS_DIR}

      podman secret rm --all
      podman secret create --env=true GITLAB_CICD_BOT_TOKEN   GITLAB_CICD_BOT_TOKEN
      podman secret create            glab-config-file        ${GLAB_CONFIG_FILE}
      podman secret create            netrc                   ${NETRC}

      IMAGE_RUN_CLI_ARGS=()
      IMAGE_RUN_CLI_ARGS+=(--rm)
      IMAGE_RUN_CLI_ARGS+=(--tty)
      IMAGE_RUN_CLI_ARGS+=(--secret glab-config-file,type=mount,target=/root/config/glab/config.yml,mode=0666)
      IMAGE_RUN_CLI_ARGS+=(--secret netrc,type=mount,target=/root/.netrc)
      IMAGE_RUN_CLI_ARGS+=(--secret GITLAB_CICD_BOT_TOKEN,type=env)
      IMAGE_RUN_CLI_ARGS+=(--volume ${JOB_ARTIFACTS_DIR}:$(dirname ${CONTAINER_RESULTS_PATH}))

      IMAGE_RUN_URI=${IMAGE_URI}:${IMAGE_INTERIM_TAG}
  script:
    - |
      # --- image unit-test --------------------------------------------------
      echo "📋 Unit testing ${IMAGE_URI}:${IMAGE_INTERIM_TAG}"
      podman run "${IMAGE_RUN_CLI_ARGS[@]}" ${IMAGE_RUN_URI}
  artifacts:
    paths:
      - ${JOB_ARTIFACTS_DIR}
    reports:
      junit: ${JOB_ARTIFACTS_DIR}/**.xml
    when: always
    expire_in: 1 week


# ============================================================================
# Use Google Container Structure Test to validate this image
.image-structure-test:
  extends: .image-build
  stage: test
  variables:
    CST_CONFIG_FILEPATH: tests/container-structure-test.yml
    IMAGE_BUILD_PRINT_CLI_TABLE: false
  before_script:
    - |
      # --- image-structure-test (before) ------------------------------------
      if [[ -f ${IMAGE_CONTEXT}/${CST_CONFIG_FILEPATH} ]]; then
        CST_CONFIG_FILEPATH=${IMAGE_CONTEXT}/${CST_CONFIG_FILEPATH}
      elif [[ ! -f ${CST_CONFIG_FILEPATH} ]]; then
        echo "❌ Error:  Container Structure Test config file not found"
        echo "           Path: ${CST_CONFIG_FILEPATH}"
        exit 10
      fi
    - !reference [.helpers/image-structure-test/setup,        before_script]
    - !reference [.image-build,                               before_script]
    - !reference [default,                                    before_script]
  script:
    - |
      # --- image-structure-test ---------------------------------------------
      IMAGE_STRUCTURE_TEST_CLI_ARGS=()
      IMAGE_STRUCTURE_TEST_CLI_ARGS+=(test)
      IMAGE_STRUCTURE_TEST_CLI_ARGS+=(--output junit)
      IMAGE_STRUCTURE_TEST_CLI_ARGS+=(--test-report ${JOB_ARTIFACTS_DIR}/structure-test-results.xml)
      IMAGE_STRUCTURE_TEST_CLI_ARGS+=(--image ${IMAGE_URI}:${IMAGE_INTERIM_TAG})
      IMAGE_STRUCTURE_TEST_CLI_ARGS+=(--config ${CST_CONFIG_FILEPATH})

      echo "⤵️ Pulling ${IMAGE_URI}:${IMAGE_INTERIM_TAG}..."
      podman image pull --quiet ${IMAGE_URI}:${IMAGE_INTERIM_TAG}

      # ----------------------------------------------------------------------
      # Run the structure test
      #
      #   - We disable the "exit on any error" logic, but capture the exit code
      #   - This allows us to print additional failure information to the Job
      #     log to make the failure investigation easier
      set +e
      echo "📋 Structure testing ${IMAGE_URI}"
      container-structure-test "${IMAGE_STRUCTURE_TEST_CLI_ARGS[@]}"
      CST_EXIT_CODE=$?
      set -e

      if [[ ${CST_EXIT_CODE} -ne 0 ]] ; then
        echo "❌ container-structure-test FAILED"

        if [[ -f ${JOB_ARTIFACTS_DIR}/structure-test-results.xml ]]; then
          xq --color ${JOB_ARTIFACTS_DIR}/structure-test-results.xml
        fi
      fi

      exit ${CST_EXIT_CODE}
    - !reference [.helpers/image-structure-test/teardown, before_script]
  artifacts:
    paths:
      - ${JOB_ARTIFACTS_DIR}
    reports:
      junit: ${JOB_ARTIFACTS_DIR}/**.xml
    when: always
    expire_in: 1 week


# ============================================================================
# Promotes this project's image by renaming from the interim build tag to the
# appropriate refs (e.g., CI_COMMIT_REF_NAME, GITLABCI_RELEASE_TRAIN, SEMANTIC_VERSION_SLUG)
.image-promote:
  extends: .image-base
  stage: publish
  interruptible: false
  variables:
    IMAGE_PROMOTE_DEFAULT_BRANCH_VERSION_SLUG: true
    IMAGE_PROMOTE_RELEASE_TRAIN: true
    IMAGE_PROMOTE_SEMANTIC_VERSION_SLUG: true
  before_script:
    - !reference [.image-base,  before_script]
    - |
      # --- image promote (before) -------------------------------------------
      declare -A IMAGE_PROMOTE_TAGS

      IMAGE_PROMOTE_TAGS["Commit Ref"]=${CI_COMMIT_REF_NAME//\//-}

      if [[ -n "${DEFAULT_BRANCH_VERSION_SLUG}" && ${IMAGE_PROMOTE_DEFAULT_BRANCH_VERSION_SLUG} == true ]]; then
        IMAGE_PROMOTE_TAGS["Default Branch"]=${DEFAULT_BRANCH_VERSION_SLUG}
      fi

      if [[ -n "${RELEASE_TRAIN}" && ${IMAGE_PROMOTE_RELEASE_TRAIN} == true ]]; then
        IMAGE_PROMOTE_TAGS["Release Train"]=${RELEASE_TRAIN}
      fi

      if [[ -n "${SEMANTIC_VERSION_SLUG}" && ${IMAGE_PROMOTE_SEMANTIC_VERSION_SLUG} == true ]]; then
        IMAGE_PROMOTE_TAGS["Semantic Version"]=${SEMANTIC_VERSION_SLUG}
      fi
  script:
    - |
      # --- image-promote ----------------------------------------------------
      for title in "${!IMAGE_PROMOTE_TAGS[@]}"; do
        tag=${IMAGE_PROMOTE_TAGS["${title}"]}

        echo "🚀 Publishing ${title} tag: ${IMAGE_URI}:${tag}"
        skopeo copy --quiet docker://${IMAGE_URI}:${IMAGE_INTERIM_TAG}  \
                            docker://${IMAGE_URI}:${tag}
      done
    - !reference [.image-release-notes, script]
  artifacts:
    paths:
      - ${RELEASE_NOTES_DIR}


# ============================================================================
.image-release-notes:
  script:
    - |
      # --- image release notes ----------------------------------------------
      mkdir -p ${RELEASE_NOTES_DIR}/image

      IMAGE_RELEASE_NOTES_FILEPATH=${RELEASE_NOTES_DIR}/image/${CI_JOB_NAME_SLUG}.md

      SECTION_TITLE=${IMAGE_NAME}
      if [[ -z "${SECTION_TITLE}" ]]; then
        SECTION_TITLE=$(basename ${IMAGE_URI})
      fi

      echo "### Image: ${SECTION_TITLE}"  >> ${IMAGE_RELEASE_NOTES_FILEPATH}
      echo ""                             >> ${IMAGE_RELEASE_NOTES_FILEPATH}

      for title in "${!IMAGE_PROMOTE_TAGS[@]}"; do
        tag=${IMAGE_PROMOTE_TAGS["${title}"]}

        # --- Append the tag information to the Release Notes:
        echo "- ${title}"                               >> ${IMAGE_RELEASE_NOTES_FILEPATH}
        echo ""                                         >> ${IMAGE_RELEASE_NOTES_FILEPATH}
        echo "  \`\`\`bash"                             >> ${IMAGE_RELEASE_NOTES_FILEPATH}
        echo "  podman image pull ${IMAGE_URI}:${tag}"  >> ${IMAGE_RELEASE_NOTES_FILEPATH}
        echo "  \`\`\`"                                 >> ${IMAGE_RELEASE_NOTES_FILEPATH}
        echo ""                                         >> ${IMAGE_RELEASE_NOTES_FILEPATH}
      done
