spec:

  inputs:
    # ------------------------------------------------------------------------
    # These settings affect the image artifact
    name:
      description: The short name of the image, relative to the Project
                   fully qualified path (<group-namespace>/<project>).
      type: string
      default: ''


    # ------------------------------------------------------------------------
    # These settings affect the building of the image
    dockerfile:
      description: Relative path to the Dockerfile used to build the image
                   (default is "Dockerfile")
      type: string
      default: Dockerfile

    context:
      description: Relative path to the image build context (default is the
                   root directory of the project)
      type: string
      default: .

    target:
      description: The image build target, if applicable
      type: string
      default: ''

    ignorefile:
      description: The relative path to the ignorefile, if applicable
      type: string
      default: .dockerignore

    build_args:
      description:  |
                    Build arguments and their values, which are passed to
                    'podman build...' where they are may be used within the
                    Dockerfile in the same way that environment variables are,
                    but which are not added to environment variable list in
                    the  resulting image's configuration.

                    Format: <name>=<value>

                    Examples:
                      - BASE_IMAGE=quay.io/podman/stable:v5.8.2
                      - MY_URL=https://example.com/my/url

                    NOTE: The following build-args are automatically provided:
                          - CI_COMMIT_REF_NAME
                          - CI_COMMIT_SHA
                          - CI_REGISTRY
                          - CI_REGISTRY_IMAGE
                          - CI_SERVER_URL
      type: array
      default: []

    build_secrets:
      description:  |
                    Pass secret information to be used in the Dockerfile for
                    building images in a safe way that will not end up stored
                    in the final image, or be seen in other stages.

                    Format: id=<id>//src=<path> or id=<id>//env=<env>

                    Example:
                      - id=my-password-file//src=/path/to/file (usually a GitLab CI/CD file variable)
                      - id=my-password//env=MY_PASSWORD        (usually a GitLab CI/CD variable)

                    NOTE: GitLab interprets comma (,) as the separator between
                          items in an array.  Therefore, we use double-forward-
                          slash (//) as the separator between the id and src
                          or id and env.  Internally, the double-forward-slash
                          is converted to a comma before sending to Podman.
                          See examples above.

                    NOTE: The following secrets are automatically provided:
                          - glab-config-file (file)
                          - netrc (file)
                          - GITLAB_CICD_BOT_TOKEN (env)
      type: array
      default: []

    build_labels:
      description:  |
                    Image metadata

                    Format: <label>=<value>

                    Examples:
                      - my.label=${MY_VAR}

                    NOTE: The following labels are automatically applied:
                          - org.opencontainers.image.created: CI_PIPELINE_CREATED_AT
                          - org.opencontainers.image.title: CI_PROJECT_TITLE
                          - org.opencontainers.image.description: CI_PROJECT_DESCRIPTION
                          - org.opencontainers.image.url: CI_PROJECT_URL
                          - org.opencontainers.image.version: CI_COMMIT_REF_SLUG
                          - org.opencontainers.image.revision: CI_COMMIT_SHA
      type: array
      default: []

    build_cache_mode:
      description:  Controls (potential) image build cache

                    - default   Enables both to/from caches, but 'to' will only
                                be used if this Pipeline is for a protected ref
                    - from      Enables the 'from' cache
                    - to        Enables the 'to' cache, but only if this
                                Pipeline is for a protected ref
                    - force     Forces both to/from caches
      type: string
      options:
        - default
        - from
        - to
        - force
        - none
      default: default

    build_stage:
      description: Assigns the Pipeline stage for the 'image build' Job
      type: string
      default: build

    build_needs:
      description: DAG specification for the 'image build' Job
      type: array
      default: []

    # ------------------------------------------------------------------------
    # These settings affect the unit testing of the image
    #
    # NOTE: Right now, there is an assumption that the 'unit-test' target uses
    #       the same Dockerfile, ignorefile, and context as the default
    #       build target.  This may need to be revisited.
    unit_test_enabled:
      description: If true, the image will be unit tested
      type: boolean
      default: true

    unit_test_target:
      description: If not empty, the image will be unit tested by building and
                   executing the corresponding target
      type: string
      default: unittest

    unit_test_container_results_path:
      description: The location at which the image's unit test will write the
                   the result xUnit file *within the running container*.
                   This Job will mount an empty directory at this location in
                   order to receive the file.
      type: string
      default: /var/tmp/test-results.xml

    unit_test_stage:
      description: Assigns the Pipeline stage for the 'image unit-test' Job
      type: string
      default: test


    # ------------------------------------------------------------------------
    # These settings affect the structure testing of the image
    structure_test_enabled:
      description: If true, the image will be structure tested
      type: boolean
      default: true

    structure_test_filename:
      description: The test configuration file per https://github.com/googlecontainertools/container-structure-test
      type: string
      default: tests/image-structure-tests.yml

    structure_test_stage:
      description: Assigns the Pipeline stage for the 'image structure-test' Job
      type: string
      default: test


    # ------------------------------------------------------------------------
    # These settings affect the promoting of the image

    promote_release_train:
      description:  If true, tag and push the Release Train version (only
                    applicable if the commit has a corresponding Release Train)
      type: boolean
      default: true

    promote_semantic_version:
      description:  If true, tag and push the Semantic Version for the image
      type: boolean
      default: true

    promote_mode:
      description:  Sets the promotion mode for this Pipeline.  Default - 'protected'
      type: string
      options:
        - protected   # Only protected refs are pushed to the container registry (default)
        - skip        # Do not push refs (including protected) to the container registry
        - force       # Push refs (including unprotected) to the container registry.
      default: protected

    promote_stage:
      description:  Assigns the Pipeline stage for the 'image promote' Job
      type: string
      default: publish


    release:
      description: |
                    If true, the Pipeline will include a 'release' Job.

                    NOTE: Only one 'release' Job should execute within a Pipeline.
      type: boolean
      default: true

    # ------------------------------------------------------------------------
    # These settings affect Job names for all Jobs instantiated by the component
    job_name_prefix:
      description: Optional prefix for the Job names
      type: string
      default: ''

    job_name_suffix:
      description: Optional suffix for the Job names
      type: string
      default: ''


---


# ============================================================================
include:


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/semver@release/0.2
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/release@release/0.2
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/foundation/merge-forward@release/0.2


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/image/build@release/0.1
    inputs:
      name: $[[ inputs.name ]]
      dockerfile: $[[ inputs.dockerfile ]]
      context: $[[ inputs.context ]]
      target: $[[ inputs.target ]]
      ignorefile: $[[ inputs.ignorefile ]]
      build_args: $[[ inputs.build_args ]]
      build_secrets: $[[ inputs.build_secrets ]]
      build_labels: $[[ inputs.build_labels ]]
      cache_mode: $[[ inputs.build_cache_mode ]]
      stage: $[[ inputs.build_stage ]]
      needs: $[[ inputs.build_needs ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/image/unit-test@release/0.1
    inputs:
      name: $[[ inputs.name ]]
      dockerfile: $[[ inputs.dockerfile ]]
      context: $[[ inputs.context ]]
      target: $[[ inputs.unit_test_target ]]
      ignorefile: $[[ inputs.ignorefile ]]
      build_args: $[[ inputs.build_args ]]
      build_secrets: $[[ inputs.build_secrets ]]
      container_test_results_path: $[[ inputs.unit_test_container_results_path ]]
      stage: $[[ inputs.unit_test_stage ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]
    rules:
      - if: '"$[[ inputs.unit_test_enabled ]]" == "true"'


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/image/structure-test@release/0.1
    inputs:
      name: $[[ inputs.name ]]
      target: $[[ inputs.target ]]
      context: $[[ inputs.context ]]
      structure_test_filename: $[[ inputs.structure_test_filename ]]
      stage: $[[ inputs.structure_test_stage ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]
    rules:
      - if: '"$[[ inputs.structure_test_enabled ]]" == "true"'


  # --------------------------------------------------------------------------
  - component: $CI_SERVER_FQDN/kerrys-learning-lab/devsecops/cicd-catalog/image/promote@release/0.1
    inputs:
      name: $[[ inputs.name ]]
      target: $[[ inputs.target ]]
      promote_release_train: $[[ inputs.promote_release_train ]]
      promote_semantic_version: $[[ inputs.promote_semantic_version ]]
      promote_mode: $[[ inputs.promote_mode ]]
      stage: $[[ inputs.promote_stage ]]
      job_name_prefix: $[[ inputs.job_name_prefix ]]
      job_name_suffix: $[[ inputs.job_name_suffix ]]
